/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useThree } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Obj02: THREE.Mesh;
    Obj01: THREE.Mesh;
    Obj03: THREE.Mesh;
    Obj04: THREE.Mesh;
  };
  materials: {
    ['Sneackers']: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { viewport } = useThree();
  console.log(`🚀 ~ viewport`, viewport);
  const { nodes, materials } = useGLTF('/models/sneackers.glb') as GLTFResult;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, -1, 0]}
      rotation={[Math.PI / 360, 0.8, 0.1]}
      scale={viewport.width < 4.5 ? viewport.width * 0.2 : viewport.width * 0.1}
    >
      <mesh geometry={nodes.Obj02.geometry} material={materials['Sneackers']} />
      <mesh geometry={nodes.Obj01.geometry} material={materials['Sneackers']} />
      <mesh geometry={nodes.Obj03.geometry} material={materials['Sneackers']} />
      <mesh geometry={nodes.Obj04.geometry} material={materials['Sneackers']} />
    </group>
  );
}

useGLTF.preload('/models/sneackers.glb');
